登录:
 - 登录用户名: "//*[@placeholder='请输入用户名']"                                      # 用户名 输入框
 - 登录密码: "//*[@placeholder='请输入密码']"                                           # 密码 输入框
 - 登录按钮: "//*[@type='button']"                                                           # 登录按钮
 - 确定按钮: "//*[@type='button'][2]/span"                                             # 确认登录
 - 操作员名称: "//*[@class='user']/span/button/span"                            # 验证登录后右上角的名称是否正确
 - 验证码: "//*[@placeholder='验证码']"                                                  # 验证码
全局:
 - 模块: "//*[@alt='{0}']"                                                                        # 菜单上的模块
 - 菜单: "//span[contains(text(), '{0}')]"                                                  # 左侧菜单
 - 子菜单: "//li[{0}]/ul/li[text()='{1}']"                                                     # 左侧子菜单
 - 查询按钮: "//button/span[contains(text(), '{0}')]"                              # 各个页面上的查询按钮
 - 提示框: "//div[@role='alert']"                                                          # 提示框
 - 提示框文本: "//div[@role='alert']/p"
 - 弹窗: "//*[@class='el-message-box']"                                             # 弹窗
 - 侧边弹窗: "//div[@class='side__wrapper common__side_form']"     # 侧边弹窗
 - 侧边弹窗叉: "//i[@class='el-icon-close']"
 - 新增/编辑-输入: "//label[contains(text(),'{0}')]/following-sibling::div"   # 可输入的框，传输入框名称
 - 新增/编辑-输入框: "//label[text()='{0}']/../div/div/input"   # 可输入的框，传输入框名称
 - 新增/编辑-单选按钮: "//label[contains(text(),'{0}')]/following-sibling::div//label[{1}]"   # 单选按钮，传入参数名和值（从左到右为1，2，......）
 - 删除确定/取消: "//div[@aria-label='提示']/div/div[3]/button[{0}]"
 - 复选框叉: "//label[contains(text(),'{0}')]/following-sibling::div//span[@class='el-input__suffix']"
 - 已选项取消的叉: "//p[contains(text(),'{0}')]/../div[{1}]/div/span/span/i"
 - 侧边弹窗底部按钮: "//div[@class='edit__footer border']//span[contains(text(),'{0}')]"    #侧边弹窗底部的按钮
 - 表格数据: "//*/tbody/tr"                                                                # 获取页面的数据
 - 表格第一条数据: "//div[contains(@class,'el-table__body-wrapper')]//tbody/tr[1]"
 - 表格第一条数据操作列: "//div[contains(@class,'el-table__body-wrapper')]//tbody/tr[1]/td[contains(@class,'is-hidden')]"
   # 不知道谁写的，好像文件中没有用到，尝试用了下也不行，先注释，后面没人用或改就删除
# - 表格全选: "//div[@class='el-table__header-wrapper']//span[@class='el-checkbox__input is-checked']"
 - 操作列选项: "//div[@aria-hidden='false']//div[contains(text(),'{0}')]"
 - 筛选项: "//div[@class='header__line'][{0}]/div[{1}]"                               # 筛选项
 - 筛选-单选列表: "//div[@x-placement='bottom-start']/div[1]/div[1]/ul/li/span[text()='{0}']"       # 点击 筛选项弹出的单选列表
 - 筛选-输入框: "//input[@placeholder='{0}']"                                   # 可输入选项框
 - 右上按钮: "//div[@class='header__ops']/button[{0}]"                    # 获取右上角的按钮，从左到右依次传1，2，3，......
 - 表格标题头: "//thead[@class='has-gutter']/tr/th"                                             # 获取页面的数据
 - 表格某一行的数据: "//div[contains(@class,'el-table__body-wrapper')]//tbody/tr[{0}]"   #随机一行数据，自己传参
 - 列设置按钮: "//div[@class='header__line']/div/span[contains(text(),'{0}')]"   #点击 上方那个列设置的
 - 列设置里面的选项: "//ul[@class='list-group']/span/li[contains(text(),'{0}')]"    #点击 列设置里面的选项
 - 列设置里面的全选: "//ul[@class='list-group']/following-sibling::li"                               # 点击 列设置里面的全选
 - 分页: "//span[@class='page__count']"    # 使用elements查找，一个页面有2个，分别是xx页/xx条数据，有的页面会有4个，自己做好判断
 - 弹出窗口-叉: "//*[contains(@aria-label,'{0}')]//button[@aria-label='Close']/i"    #根据弹出的窗口的唯一标题名，找它的叉
采访:
  征订目录预订:
    # 新增信息-输入定位: "//label[text()='{0}']/following-sibling::div/div/input"    # 获取左边的文本，定位到右边的输入框
    # 新增/编辑窗口属于<div class='app_content'>下的一个div里，新增排第一，编辑排第二，两个窗口的参数时基本一样的
   - 采访-新增/编辑-输入: "//div[@*='width: 850px;']/div[2]/div[1]/div/div/form/div/div[2]/label[text()='{0}']/following-sibling::div/div/input"
   - 采访-新增/编辑-按钮: "//div[@*='width: 850px;']/div[3]/div/div[2]/button/span[text()='{0}']"
   - 采访-删除信息-确定: "//div[@aria-label='提示']/div/div[3]/button[{0}]"
   - 采访-表格数据: "//*/tbody/tr[{0}]/td[4]"    # 获取表格数据，{0}决定获取的数据
   - 采访-表格数据链接: "//*/tbody/tr[{0}]/td[3]/div/span"
   - 采访-表格数据勾选: "//*/tbody/tr[{0}]/td[1]/div/label"
  预订单管理:
   - 采访-清空订单信息-确定: "//div[@aria-label='提示']/div/div[3]/button[{0}]"               #点击确定按钮
   - 预订单标题名: "//div[contains(@class,'el-table__body-wrapper')]//tbody/tr[{0}]/td[3]"   #随机一行的数据的预订单的名字
   - 预订单详情内的标题: "//div[@class='c-content-header']/div/span"                         #点击某个预订单，获取预订单名字
   - 设为工作预订单列: "//div[contains(@class,'el-table__body-wrapper')]//tbody/tr[{0}]/td[10]/div/span/i"    #点击随机一行的五角星列
   - 催缺信息页标题: "//*/div[@class='p-acq_cqxx']/div[1]/div[1]/div[1]/span[2]"    #获取催缺信息页标题
   - 表格某一行的勾选框: "//div[contains(@class,'el-table__body-wrapper')]//tbody/tr[{0}]/td[1]"   #随机一行数据的勾选框，自己传参
  直接预订:
   - 新增-编目-右下方按钮: "//div[@class='editor__footer_bottom']/div[3]/button[{0}]/span"    #编目的右下方按钮，传数值确目标按钮
   - 简单编目-输入: "//div[@class='c-tmms']/div[3]/div/div[{0}]/div[2]/textarea"   #简单编目输入内容的表格,传参找目标表格，11为正题名
   - 书目信息-预订-预订配置: "//div[@class='top-right']/div[2]/form/div[{0}]/div/div/input"   #目标书籍的预订数据的配置
   - 预订配置-下方按钮: "//div[@class='acq-smyd three-distribution']/div[2]/div[2]/button[{0}]/span"   #预订配置的保存和取消按钮
   - 设为默认参数按钮: "//div[@class='content content__full']/p[2]/div"   #预订配置的保存和取消按钮
   - 默认参数表格内容: "//div[@class='content content__full']/div/form/div[1]/div[{0}]/div/div/input"    #预订参数设置表格里的参数
   - 默认参数表格-下方操作按钮: "//div[@class='app_content']/div/div[4]/div[3]/div/div[2]/button[{0}]"  #预订参数设置表格里的保存和取消
   - 默认参数表格-下方重置按钮: "//div[@class='app_content']/div/div[4]/div[3]/div/div[1]/button[1]"  #预订参数设置表格里的重置按钮
  图书验收处理:
   - 采访-验收单-备注: "//label[@for='beizhu']/following-sibling::div/div/textarea"
   - 验收确定/取消: "//div[@aria-label='批量验收']/div/div[3]/button/span[contains(text(),'{0}')]"
   - 编目-简单编目/MARC编目: "//div[@class='tabs']/div[{0}]"
   - 编目-简单编目-添加父记录: "//div[@class='el-scrollbar__view']/div[1]//button[@title='ALT+I']"
   - 编目-简单编目-查看连接记录: "//div[@class='el-scrollbar__view']/div[1]//button[@title='ALT+V']"
   - 编目-简单编目-筛选项:  "//div[@class='c-tmms']//div[@class='el-select el-select--mini'][{0}]/div[1]//input[@type='text']"# 获取筛选项输入框，从左到右依次传1，2，3，......
   - 编目-MARC编目-筛选项:  "//div[@class='c-marcms']//span[contains(text(), '分编类型')]/following-sibling::div[{0}]"# 获取筛选项输入框，从左到右依次传1，2，3，......
   - 编目-MARC编目-上方按钮: "//div[@class='c-marcms']//div[@class='header']/div//span[contains(text(),'{0}')]"
   - 编目-右下角按钮: "//div[@class='editor__footer']//button[@type='button']/span[contains(text(),'{0}')]"
   - 编目弹窗-按钮: "//div[@aria-label='拼音字段生成多音字选择']//button[@type='button']/span[contains(text(),'确定')]"
   - 父记录-移除: "//div[@style='display: flex;']//button[@type='button']"
   - 移除-确定: "//*[@class='el-message-box']//*[@type='button']/span[contains(text(),'确定')]"
   - 添加父记录-查询输入框: "//div[@aria-label='添加父记录']//div[@class='header__line']/div[{0}]//input[@type='text']"  # 获取筛选项以及输入框，从左到右依次传1，2，3，......
   - 添加父记录-查询: "//div[@aria-label='添加父记录']//div[@class='header__line']/button"
   - 添加父记录-确认: "//*[@class='el-dialog__wrapper']/div/div[3]/span/button[1]/span"
   - 添加父记录-取消: "//*[@class='el-dialog__wrapper']/div/div[3]/span/button[2]/span"
   - 按钮: "//div[@class='header__ops']/button[1]/span[contains(text(),'新增')]"
   - 简单编目-书目信息输入: "//div[@class='tmsms__wrapper_row'][{0}]/div[2]/textarea"
   - 简单编目-原书信息保存: "//div[@aria-label='提示']//button[@type='button']/span[contains(text(),'保存')]"
   - 编目-图书信息查询结果: "//div[@class='el-scrollbar__view']/button/following-sibling::div[1]"
   - 编目-图书信息查询结果勾选: "//div[@class='el-scrollbar__view']/button/following-sibling::div[2]//span[@class='el-checkbox__inner']"
   - 编目-图书信息查询合并按钮: "//div[@class='el-scrollbar__view']/button/span"
   - 编目-图书信息合并提示窗口: "//div[@aria-label='提示']//span[contains(text(),'合并')]"
   - 编目-取消审校定位元素: "//div[@class='editor__footer']//button[@type='button'][4]"
   - 编目-审校/取消审校窗口确定: "//div[@aria-label='提示']//button[@type='button']/span[contains(text(),'确定')]"
   - 编目-MARC编目-字段识别: "//div[@class='body scroll']//tr[@class='el-table__row'][{0}]/td[3]/div/input"
   - 编目-MARC编目-字段内容: "//div[@class='body scroll']//tr[@class='el-table__row'][{0}]/td[5]/div//div/textarea"
   - 编目-粘贴网页MARC-书目信息输入: "//div[@class='el-dialog__wrapper']/div[@aria-label='粘贴网页MARC']//textarea[@class='el-textarea__inner']"
   - 编目-粘贴网页MARC-确定: "//div[@class='marc-editor']//div[@aria-label='粘贴网页MARC']//span[contains(text(),'确定')]"
   - 编目-粘贴网页MARC-重置恢复: "//div[@aria-label='提示']//span[contains(text(),'恢复')]"
编目:
 编目管理:
   - 编目-筛选项: "//div[@class='header__line'][{0}]/div[{1}]/div[{2}]"
   - 编目-筛选项输入框: "//div[@class='header__line'][{0}]/div[{1}]/div[{2}]/input"
   - 编目-表格-数据: "//div[contains(@class,'el-table__body-wrapper')]//tbody/tr/td[{0}]/div"     # 获取单独一列的数据，使用elements获取
   - 编目-筛选项数量: "//div[@class='header__line'][{0}]/div"                        # 查看筛选项数量，传值选择第一行筛选项或第二行筛选项
   - 编目-加减筛选项按钮: "//i[@class='{0}']"                                        # 根据class定位筛选项加减按钮，传的值有el-icon-remove，el-icon-circle-plus
   - 编目-勾选框: "//input[@true-value='{0}']"                                      # 审校、推荐的勾选框（非数据勾选框，别用错了），传的值为 已审核，已推荐
   - 编目-拼音弹窗: "//*[@aria-label='拼音字段生成多音字选择']"
   - 编目-审校/推荐-勾选框: "//input[@true-value='{0}']/preceding-sibling::span"
   - 编目-审校/推荐-是否勾选: "//input[@true-value='{0}']"                                      # 审校、推荐的勾选框（非数据勾选框，别用错了），传的值为 已审核，已推荐
   - 编目-零馆藏书目-勾选框: "//div[@class='header__line'][1]/label/span[1]"
   - 编目-零馆藏书目-是否勾选: "//div[@class='header__line'][1]/label/span[1]/input"
   - 编目-右上更多/导出按钮: "//div[@class='header__ops']/div[{0}]"      # 右上按钮定位不到，特殊项兼容下:(
   - 编目-拼音/推荐/分编弹窗: "//*[contains(@aria-label,'{0}')]"                                      # 屏幕中间的弹窗，用来确认是否存在，传的值为：拼音字段生成多音字选择，图书推荐，修改分编类型
   - 编目-推荐关闭按钮: "//*[@aria-label='图书推荐']/div[1]/button"                      # 拼音字段生成多音字选择 没有关闭按钮（右上角的x图标）
   - 编目-推荐多选列表: "//div[@class='el-dialog__body']/div[1]/div[1]/input"          # 点击列表，弹出多选框
   - 编目-推荐备注: "//div[@class='el-dialog__body']/div[2]/input"
   - 编目-推荐多选列表-是否存在: "//*[@x-placement='bottom-start']/p"                    # 判断这个元素在不在，False确认推荐的多选列表有没有值
   - 编目-推荐多选列表-值: "//*[@x-placement='bottom-start']/div[1]/div[1]/ul/li[1]"    # 选择第一条值
   - 编目-推荐取消按钮: "//span[contains(text(), '推 荐')]/../following-sibling::button"
   - 编目-更多/导出单选列表: "//*[@id='app']/following-sibling::ul[last()]/li[{0}]"        # 右上的更多 和 导出 两个按钮都是在id=app的div之外的，而且点击哪个，就会跳到最后一个
   - 编目-修改分编类型-筛选项: "//*[text()='分编类型：']/following-sibling::div/div/input"
   - 编目-修改分编类型-单选列表: "//*[text()='分编类型：']/ancestor::div[@class='el-dialog__wrapper']/following-sibling::div/div/div/ul/li/span[text()='{0}']"
   - 编目-修改分编类型-按钮: "//*[contains(@aria-label,'修改分编类型')]/div[3]/span/div[2]/button/span[text()='{0}']"
   - MARC编辑-简单编目-书目信息输入: "//*[@title='{0}']/following-sibling::div/textarea"              # 左边的文本定位右边的输入框，比如ISBN、正题名
   - MARC编辑-MARC编目-书目信息输入: ""
   - MARC编辑-简单/MARC编目: "//div[@class='tabs']/div[text()='{0}']"                       # 输入 简单编目 ， MARC编目 （有空格）
   - MARC编辑-左上单选列表: "//div[@class='{0}']//span[text()='{1}']/following-sibling::div[1]//input"    # 输入左边文本定位右边单选框，第一个值为：c-tmms，c-marcms；第二个值为：分编类型： 检索来源： 模板：
   - MARC编辑-左上按钮: "//div[@class='c-marcms']//span[contains(text(),'{0}')]"
   - MARC编辑-左上单选按钮: "//div[@class='c-marcms']//span[contains(text(),'字段帮助')]/preceding-sibling::span//input"
   - MARC编辑-右下按钮: "//div[@class='editor__footer']//button/span[contains(text(),'{0}')]"
   - MARC编辑-保存后-文本: "//span[text()='操作详情']/parent::label/following-sibling::div"
   - MARC编辑-保存后-单选列表: "//ul/li[text()='{0}']"

 文献移送:
   - 编目-已交送列: "//div[contains(@class,'el-table__body-wrapper')]//tbody/tr[{0}]/td[7]"  #获取已经交送列的值
 编目统计:
   - 随机一行中随机一列的值: "//div[contains(@class,'el-table__body-wrapper')]//tbody/tr[{0}]/td[{1}]"  #获取目标行的目标列的值
   - 书标打印-弹出窗口: "//*[contains(@aria-label,'{0}')]"  #根据标题匹配窗口
运营:
  订购处理:
   - 运营-新增/编辑-输入: "//label[contains(text(),'{0}')]/following-sibling::div//div[@class='el-select__tags']/input"
特色:
  资源管理:
   - 特色-删除弹框-确定/取消: "//div[@aria-label='删除分类']/div/div[3]/button[{0}]"


